export const catBenches = [
  { id: "1", name: "Principal Bench New Delhi" },
  { id: "2", name: "Chandigarh Bench" },
  { id: "3", name: "Mumbai Bench" },
  { id: "4", name: "Chennai Bench" },
  { id: "5", name: "Kolkata Bench" },
  { id: "6", name: "Hyderabad Bench" },
  { id: "7", name: "Ahmedabad Bench" },
  { id: "8", name: "Jaipur Bench" },
  { id: "9", name: "Lucknow Bench" },
  { id: "10", name: "Bhopal Bench" },
  { id: "11", name: "Patna Bench" },
  { id: "12", name: "Guwahati Bench" },
  { id: "13", name: "Ernakulam Bench" },
  { id: "14", name: "Cuttack Bench" },
  { id: "15", name: "Jabalpur Bench" },
  { id: "16", name: "Bangalore Bench" },
  { id: "17", name: "Jodhpur Bench" },
  { id: "18", name: "Allahabad Bench" },
  { id: "19", name: "Nagpur Bench" },
  { id: "20", name: "Madurai Bench" },
];
