export const ncltBenches = [
  { id: "1", name: "New Delhi" },
  { id: "2", name: "Mumbai" },
  { id: "3", name: "Chennai" },
  { id: "4", name: "Kolkata" },
  { id: "5", name: "Ahmedabad" },
  { id: "6", name: "Bengaluru" },
  { id: "7", name: "Hyderabad" },
  { id: "8", name: "Allahabad" },
  { id: "9", name: "Chandigarh" },
  { id: "10", name: "Guwahati" },
  { id: "11", name: "Jaipur" },
  { id: "12", name: "Kochi" },
  { id: "13", name: "Cuttack" },
  { id: "14", name: "Indore" },
  { id: "15", name: "Amaravati" },
  { id: "16", name: "Jaipur Circuit Bench" },
];
